### ISSUE TITLE
Crash Report - Fabric 0.6.3+build.167 on 1.14.4

### ISSUE THREAD

**Issue by Iamthedogev** [vini2003/Buffer#4]
https://paste.ee/p/4pZQ5

I'm unsure what mod is causing the issue here - while making a personal modpack, I singled out that using Bamboo Everything (https://www.curseforge.com/minecraft/mc-mods/bamboo-everything-fabric) and Buffer (https://www.curseforge.com/minecraft/mc-mods/buffer) together was causing the game to crash on launch. I have made this report on both mods in the hope to find a solution.

**Comment by vini2003** [comment]
The crash happens because of LivingEntityMixin 🤔 
I don't have that class, and Bamboo Everything doesn't have any Mixins aside a default test one (which you should really remove, @Gaz_), on GitHub so no possible conflicts.

**Comment by vini2003** [comment]
Oh, LadderAPI. So that's a thing then.

**Comment by vini2003** [comment]
These should not conflict at all. I only touch ItemEntity. Ladder API is somehow not finding the target method for the Mixin it wants to do, but this should not be related to Buffer.

@Gaz492 any clue?

**Comment by vini2003** [comment]
Seems that guy is dead.
